dist: trusty

# TODO: Some tests for Compressed OOPs fail if sudo=false
# sudo: true

language: java

jdk:
  - oraclejdk8
  - openjdk8

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - llvm-5.0-dev
    env:

env:
  global:
    - CXX=clang++-5.0
    - LLVM_CONFIG=llvm-config-5.0

branches:
  only:
    - master

notifications:
  email: false

script:
  - ./bin/run-travis-tests.sh

